name: Patch

on:
  workflow_dispatch: # 手动触发
    inputs:
      version:
        description: Version to release (x.x.x+x)
        default: 1.0.0+1
        required: true
      staging:
        description: Staging or not
        required: true
        type: choice
        options:
          - true
          - false
env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

jobs:
  job_apk:
    name: 构建android patch
    runs-on: ubuntu-latest
    env:
      version: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 编译环境设置 Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 构建签名环境
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
      - name: 设置 Shorebird
        uses: shorebirdtech/setup-shorebird@v1
      - name: 执行编译
        uses: shorebirdtech/shorebird-patch@v0
        id: shorebird-patch
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        with:
          platform: android
          # args: --release-version=${{env.version}} --staging
          args: --release-version=${{env.version}} ${{ inputs.staging == 'true' && '--staging' || '' }}

  job_ipa:
    name: 构建ios patch
    runs-on: macos-latest
    env:
      version: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 设置 Shorebird
        uses: shorebirdtech/setup-shorebird@v1
      - name: Build (ios)
        uses: shorebirdtech/shorebird-patch@v0
        with:
          platform: ios
          # args: --release-version=${{env.version}} --staging --no-codesign
          args: --release-version=${{env.version}} ${{ inputs.staging == 'true' && '--staging' || '' }} --no-codesign